# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0002_auto_20160522_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtag_set', to='mycms.ATag'),
        ),
        migrations.AlterField(
            model_name='userbrowsehistory',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
