# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0003_auto_20160522_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='mycms.Article'),
        ),
    ]
